Improve worker config, refs #13109
artefactual/atom-docs pull request #122
Opened 2019-08-07 18:20 UTC by jraddaoui

2019-08-07 18:45 UTC, fiver-watson commented on admin-manual/installation/asynchronous-jobs.rst
> +If your planing to connect multiple AtoM instances to the same Gearman server,
you're

2019-08-07 18:46 UTC, fiver-watson commented on admin-manual/installation/upgrading.rst
> +and performance of the application. Check the installation documentaion for your
Minor typo - documentation

2019-08-07 18:47 UTC, fiver-watson requested changes
2 very minor typos to fix - otherwise it looks good!

2019-08-07 18:51 UTC, fiver-watson approved these changes
Fixes look good! Might want to squash before merging but otherwise 👍

2019-08-07 18:56 UTC, merged

2019-08-07 19:00 UTC, jraddaoui commented
Thanks @fiver-watson!

2019-08-15 00:03 UTC, djjuhasz commented on admin-manual/installation/asynchronous-jobs.rst
> +If you're planing to connect multiple AtoM instances to the same Gearman server,
Typo, should be "planning"