Add storage import docs, fixes #140
artefactual/atom-docs pull request #141
Opened 2020-03-23 22:03 UTC by fiver-watson

This PR adds new documentation for the command-line physical storage import task added to AtoM 2.6.

2020-03-23 22:21 UTC, corinnemrogers requested changes
just a few minor edits, 2 discretionary and 2 typos

2020-03-23 22:21 UTC, corinnemrogers commented on admin-manual/maintenance/cli-import-export.rst
> +to existing physical storage containers, via an accompanying CSV file. Read more
this is perhaps overly pedantic, but "accompanying CSV file" sounds like the import is accompanied by a CSV file - I think you can simply remove the word "accompanying"

2020-03-23 22:21 UTC, corinnemrogers commented on admin-manual/maintenance/cli-import-export.rst
> +outside of the basic ASCII character set.  The CSV file formatting must use a
remove double space between sentences

2020-03-23 22:21 UTC, corinnemrogers commented on admin-manual/maintenance/cli-import-export.rst
> +   php synfony csv:physicalobject-import --update --skip-unmatched --multi-match="all" --partial-match --skip-rows=10 --error-log="/usr/share/nginx/atom/errors.log" --index /path/to/my/storage.csv
symfony

2020-03-23 22:21 UTC, corinnemrogers commented on admin-manual/maintenance/cli-import-export.rst
> +   php synfony csv:physicalobject-import -u -s --multi-match="all" -p -o=10 -l="/usr/share/nginx/atom/errors.log" -i /path/to/my/storage.csv
symfony

2020-03-24 14:22 UTC, fiver-watson commented
Thanks for the review! I've implemented your changes, and squashed. Let me know if you see anything else, or if I should merge this now.

2020-03-24 14:23 UTC, fiver-watson commented on admin-manual/maintenance/cli-import-export.rst
> +outside of the basic ASCII character set.  The CSV file formatting must use a
Done

2020-03-24 15:42 UTC, corinnemrogers approved these changes
Looks good!

2020-03-24 15:49 UTC, merged