Create CSV validation docs, fixes #186
artefactual/atom-docs pull request #187
Opened 2021-08-20 18:36 UTC by fiver-watson

This pull request adds new documentation to the 2.7 AtoM docs, covering the CSV validation functionality that will be introduced in AtoM release 2.7. 

Most changes are in a new `csv-validation` documentation page in the user manual. However, this PR also includes: 

* A new section in the Settings page covering the CSV validator settings for the user interface
* A new section in the command-line import/export page (Admin manual) on the CLI validation task
* Updates to both UI and CLI csv import sections, fixing links and images and referencing the CSV validation functionality wherever relevant.
* Updates to the sphinx docs index page and the ToC so that the new documentation page registers correctly

This PR, once approved, will close GitHub issue #186.

**Related Redmine issue tickets**

* https://projects.artefactual.com/issues/13508 (GUI integration and import setting)
* https://projects.artefactual.com/issues/13475 (CLI task)

2021-08-24 14:24 UTC, sromkey approved these changes
Looks good!

2021-08-24 18:55 UTC, sbreker commented
Added a few items to review/tweak. I will update the messages coming from the column count validator and get back to you.

2021-08-24 21:30 UTC, sbreker requested changes
Looks great @fiver-watson! Will be a great resource for the CSV Validator. 

I've noted a few clarifications and fixes but nothing major.

2021-08-24 21:30 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +| CsvDigitalObjectPathValidator   | All entities                               |
This should read: 'Archival Description'

2021-08-24 21:30 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +| CsvDuplicateColumnNameValidator | Archival description                       |
This should be 'All entities'.

2021-08-24 21:30 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +appear first in the summary output if duplicate columns are detected. This means
If it is an error it will be at the top of the report with any other errors, but not necessarily first.

2021-08-24 21:30 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +error because when more than one column shares the same name, AtoM does not
Omit "This means that the error state for this test is determined by the <duplicate col test>."

Following sentence: "This is an error because when more than one column...."

2021-08-24 21:30 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +   CSV rows with different lengths detected - check CSV enclosure option matches file.
Ooops. This message needs to be changed since we eliminated the 'enclosure' option because the CSV import does not actually allow the field separator and enclosure chars to be customized/specified.

2021-08-24 21:30 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +CSV and identify the problem language values. Ensure that only supported ISO
Should be "...problem script values."?

2021-08-24 21:30 UTC, sbreker commented on admin-manual/maintenance/cli-import-export.rst
> +| CsvDigitalObjectPathValidator   | All entities                             |
Same issues as webui import

2021-08-24 21:37 UTC, sbreker commented on user-manual/import-export/csv-validation.rst
> +   CSV rows with different lengths detected - check CSV enclosure option matches file.
Changed to: `CSV rows with different lengths detected - ensure CSV enclosure character is double quote ('"').`

2021-08-25 13:34 UTC, fiver-watson commented on user-manual/import-export/csv-validation.rst
> +| CsvDigitalObjectPathValidator   | All entities                               |
Woops, good catch - fixed

2021-08-25 13:34 UTC, fiver-watson commented on user-manual/import-export/csv-validation.rst
> +| CsvDuplicateColumnNameValidator | Archival description                       |
fixed

2021-08-25 13:35 UTC, fiver-watson commented on user-manual/import-export/csv-validation.rst
> +appear first in the summary output if duplicate columns are detected. This means
ok, done

2021-08-25 13:35 UTC, fiver-watson commented on user-manual/import-export/csv-validation.rst
> +error because when more than one column shares the same name, AtoM does not
done

2021-08-25 13:36 UTC, fiver-watson commented on user-manual/import-export/csv-validation.rst
> +   CSV rows with different lengths detected - check CSV enclosure option matches file.
good catch - sample output updated

2021-08-25 13:36 UTC, fiver-watson commented on user-manual/import-export/csv-validation.rst
> +CSV and identify the problem language values. Ensure that only supported ISO
haha nice catch - you can tell I did a lot of initial copy/pasting and missed that. fixed.

2021-08-25 13:36 UTC, fiver-watson commented on admin-manual/maintenance/cli-import-export.rst
> +| CsvDigitalObjectPathValidator   | All entities                             |
thanks, done

2021-08-25 13:38 UTC, fiver-watson commented
Thanks Steve! I've implemented your suggestions in an additional commit - if you want to give that a quick lookover, I will squash before merging once I get a 👍

2021-08-25 15:53 UTC, sbreker approved these changes
Looks great @fiver-watson! Thanks for making those updates.

2021-08-25 17:41 UTC, merged