Add guidance for docker memory limit
artefactual/atom-docs pull request #225
Opened 2023-07-04 08:15 UTC by J4bbi

See:
https://groups.google.com/d/msgid/ica-atom-users/4cf63896-6aa1-4744-bb0d-33984eaca9fan%40googlegroups.com?utm_medium=email&utm_source=footer

2023-07-04 23:04 UTC, anvit requested changes

2023-07-04 23:04 UTC, anvit commented on dev-manual/env/compose.rst
> +   you can increase the memory allocated to the Atom container by either adding
Hi @J4bbi ! Thanks so much for this doc update!

I'd suggest capitalizing the `M` in AtoM, but the rest looks good to go!

2023-07-05 12:36 UTC, J4bbi commented on dev-manual/env/compose.rst
> +   you can increase the memory allocated to the Atom container by either adding
I decided to leave atom there in lowercase because it's referring to the atom container, as in line 114:
`# Execute a command in the running container atom: purge database
`
Is this okay? Happy to change to whatever you like though

2023-07-05 18:29 UTC, anvit commented on dev-manual/env/compose.rst
> +   you can increase the memory allocated to the Atom container by either adding
No, this makes sense! Will approve and merge this change!

2023-07-05 18:31 UTC, anvit approved these changes

2023-07-05 18:41 UTC, merged